# Vortex RTL Files for Simulation
+incdir+$VORTEX_HOME/hw/rtl
+incdir+$VORTEX_HOME/hw/rtl/interfaces
+incdir+$VORTEX_HOME/hw/rtl/core
+incdir+$VORTEX_HOME/hw/rtl/cache
+incdir+$VORTEX_HOME/hw

# Package first
$VORTEX_HOME/hw/rtl/VX_gpu_pkg.sv

# Find all RTL files
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/interfaces/VX_ibuffer_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/interfaces/VX_commit_sched_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/interfaces/VX_fetch_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/interfaces/VX_dispatch_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/interfaces/VX_decode_sched_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/interfaces/VX_sched_csr_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/interfaces/VX_decode_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/interfaces/VX_operands_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/interfaces/VX_branch_ctl_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/interfaces/VX_issue_sched_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/interfaces/VX_warp_ctl_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/interfaces/VX_execute_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/interfaces/VX_result_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/interfaces/VX_commit_csr_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/interfaces/VX_writeback_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/interfaces/VX_dcr_bus_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/interfaces/VX_commit_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/interfaces/VX_schedule_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/interfaces/VX_scoreboard_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/tcu/VX_tcu_int.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/tcu/VX_tcu_pkg.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/tcu/VX_tcu_fedp_bhf.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/tcu/VX_tcu_fp.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/tcu/bhf/VX_tcu_bhf_fadd.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/tcu/bhf/bsg_counting_leading_zeros.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/tcu/bhf/VX_tcu_bhf_fmul.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/tcu/bhf/VX_tcu_bhf_bf16mul.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/tcu/VX_tcu_top.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/tcu/VX_tcu_unit.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/tcu/VX_tcu_fedp_dpi.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/tcu/VX_tcu_uops.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/tcu/VX_tcu_fedp_dsp.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/tcu/VX_tcu_fedp_int.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/Vortex_axi.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_schedule.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_issue.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_alu_int.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_dcr_data.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_lsu_unit.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_dispatch_unit.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_issue_slice.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_ipdom_stack.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_pe_switch.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_scoreboard.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_opc_unit.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_split_join.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_csr_data.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_core.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_decode.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_fetch.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_alu_unit.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_mem_unit_top.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_uuid_gen.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_sfu_unit.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_dispatch.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_core_top.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_ibuffer.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_gather_unit.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_issue_top.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_lsu_slice.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_commit.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_wctl_unit.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_csr_unit.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_alu_muldiv.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_operands.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_execute.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_mem_unit.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/core/VX_uop_sequencer.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/VX_trace_pkg.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_mem_scheduler.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_divider.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_pipe_register.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_serial_div.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_transpose.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_bits_insert.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_index_queue.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_scope_switch.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_stream_xpoint.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_bits_remove.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_avs_adapter.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_index_buffer.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_scope_tap.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_mem_data_adapter.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_find_first.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_pending_size.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_generic_arbiter.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_matrix_arbiter.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_bypass_buffer.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_dp_ram.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_pe_serializer.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_stream_buffer.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_popcount.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_skid_buffer.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_onehot_shift.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_stream_switch.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_elastic_adapter.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_lzc.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_sp_ram.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_rr_arbiter.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_demux.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_mem_coalescer.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_stream_pack.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_async_ram_patch.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_onehot_mux.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_shift_register.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_scan.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_mux.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_edge_trigger.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_axi_write_ack.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_stream_omega.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_ticket_lock.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_allocator.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_stream_arb.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_placeholder.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_serial_mul.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_toggle_buffer.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_nz_iterator.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_reset_relay.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_priority_encoder.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_fifo_queue.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_stream_unpack.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_pipe_buffer.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_axi_adapter.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_mem_bank_adapter.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_bits_concat.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_multiplier.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_stream_xbar.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_priority_arbiter.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_elastic_buffer.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_onehot_encoder.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_cyclic_arbiter.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/libs/VX_reduce_tree.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/VX_socket.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/VX_cluster.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/fpu/VX_fpu_dsp.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/fpu/VX_fpu_pkg.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/fpu/VX_fncp_unit.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/fpu/VX_fpu_fpnew.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/fpu/VX_fcvt_unit.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/fpu/VX_fpu_div.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/fpu/VX_fpu_ncp.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/fpu/VX_fpu_unit.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/fpu/VX_fpu_csr_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/fpu/VX_fp_classifier.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/fpu/VX_fpu_fma.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/fpu/VX_fpu_cvt.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/fpu/VX_fpu_dpi.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/fpu/VX_fp_rounding.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/fpu/VX_fpu_sqrt.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/Vortex.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/cache/VX_cache_wrap.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/cache/VX_cache_bypass.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/cache/VX_cache_bank.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/cache/VX_cache.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/cache/VX_cache_data.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/cache/VX_cache_repl.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/cache/VX_cache_top.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/cache/VX_cache_tags.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/cache/VX_cache_cluster.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/cache/VX_cache_init.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/cache/VX_cache_mshr.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/cache/VX_cache_flush.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/afu/opae/ccip_interface_reg.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/afu/opae/ccip/ccip_if_pkg.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/afu/opae/local_mem_cfg_pkg.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/afu/opae/ccip_std_afu.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/afu/opae/vortex_afu.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/afu/xrt/VX_afu_wrap.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/afu/xrt/VX_afu_ctrl.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/afu/xrt/vortex_afu.v
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/mem/VX_gbar_unit.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/mem/VX_mem_arb.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/mem/VX_lmem_switch.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/mem/VX_mem_bus_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/mem/VX_gbar_arb.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/mem/VX_gbar_bus_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/mem/VX_local_mem_top.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/mem/VX_mem_switch.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/mem/VX_lsu_mem_if.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/mem/VX_local_mem.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/mem/VX_lsu_mem_arb.sv
/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl/mem/VX_lsu_adapter.sv
