#!/usr/bin/env bash
# =============================================================================
# gen_coverage_exclude.sh  NCL NC NW NT  ->  emits a CONFIG-SPECIFIC Questa
# coverage-exclusion .do on stdout.
#
# Replaces the hand-maintained pair (coverage_exclude.do + coverage_exclude_2CL.do)
# with ONE generator that scales to ANY topology N_CLUSTERS / N_CORES / N_WARPS /
# N_THREADS. merge_coverage.sh calls it with the run's config so each config's
# report only counts coverage that is actually REACHABLE for that config.
#
# PRINCIPLE (do not violate — this is the whole point of the file):
#   Only STRUCTURALLY-DEAD coverage is excluded, and every waiver is KEYED to the
#   config that makes it dead. We NEVER exclude logic that is reachable-but-merely-
#   untested (that would inflate the number dishonestly). Reachable gaps are closed
#   with directed tests instead (e.g. vote_shfl for ALU_TYPE_OTHER), not waived.
#
# Waiver classes (the '# --- Xxx:' comments are the audit label; Questa's built-in
# -reason code is in parentheses — Questa rejects custom reason strings):
#   EOTH  third-party IP, not the Vortex DUT     (cvfpu, Berkeley HardFloat in TCU)   -> EOTH
#   EUR   config-dead tied-off interface          (L2/L3 PASSTHRU cache-side buses)    -> EUR
#   ECFG  topology-structural dead condition      (e.g. global barrier at 1 core)      -> EUR
#
# Usage:
#   scripts/gen_coverage_exclude.sh 1 1 4 4 > /tmp/excl.do
#   vsim -viewcov raw.ucdb -c -do "do /tmp/excl.do; coverage save merged.ucdb; quit -f"
#
# Verify it all matched (0 stale lines):
#   grep -c "had no effect" <dryrun.log>   # expect 0
# =============================================================================
set -euo pipefail

NCL="${1:?need NUM_CLUSTERS}"
NC="${2:?need NUM_CORES}"
NW="${3:?need NUM_WARPS}"
NT="${4:?need NUM_THREADS}"
# L2/L3 presence. Optional 5th/6th args (default 0 = the historical behaviour, so
# every existing caller is unchanged). These gate section 3: when a level is
# ENABLED its cache-side buses are LIVE LOGIC and must NOT be waived as passthru.
L2="${5:-0}"
L3="${6:-0}"

RTL="/home/samuel_ubuntu22/Vortex_UVM_GP/Vortex/hw/rtl"
TB="/home/samuel_ubuntu22/Vortex_UVM_GP/vortex_uvm_env/tb"
TOP="/vortex_tb_top/dut/vortex"

# Socket layout mirrors VX_config.vh: SOCKET_SIZE = min(4, NUM_CORES);
# NUM_SOCKETS = ceil(NUM_CORES / SOCKET_SIZE).
SOCKET_SIZE=$(( NC < 4 ? NC : 4 ))
(( SOCKET_SIZE < 1 )) && SOCKET_SIZE=1
TOTAL_CORES=$(( NCL * NC ))

core_scope() {   # $1=cluster $2=core-index-within-cluster  ->  full core scope path
  local cl=$1 co=$2
  local sk=$(( co / SOCKET_SIZE ))
  local cis=$(( co % SOCKET_SIZE ))
  echo "${TOP}/g_clusters[${cl}]/cluster/g_sockets[${sk}]/socket/g_cores[${cis}]/core"
}

echo "# ============================================================================="
echo "# AUTO-GENERATED by gen_coverage_exclude.sh for config ${NCL}CL/${NC}C/${NW}W/${NT}T"
echo "# (TOTAL_CORES=${TOTAL_CORES}, SOCKET_SIZE=${SOCKET_SIZE}). Do not edit by hand."
echo "# ============================================================================="
echo

# -----------------------------------------------------------------------------
# 1. EOTH — third-party IP by DESIGN UNIT (config-independent; module names).
#    cvfpu FP core + div/sqrt + common-cells, and the Vortex cvfpu wrapper.
# -----------------------------------------------------------------------------
echo "# --- EOTH: third-party cvfpu IP (by design unit) ---"
echo "coverage exclude -du {fpnew_*}   -reason EOTH"
echo "coverage exclude -du {*mvp*}     -reason EOTH"
echo "coverage exclude -du cf_math_pkg -reason EOTH"
echo "coverage exclude -du lzc         -reason EOTH"
echo "coverage exclude -du rr_arb_tree -reason EOTH"
echo "coverage exclude -du VX_fpu_fpnew -reason EOTH"
echo "# TCU Vortex control units (Berkeley HardFloat submodules caught by scope below)"
echo "coverage exclude -du {VX_tcu_*}  -reason EOTH"
echo

# -----------------------------------------------------------------------------
# 2. EOTH — TCU FP datapath scope, per CORE instance (Berkeley HardFloat IP:
#    fNToRecFN/recFNToFN/addRecFN/... named modules that -du {VX_tcu_*} misses).
#    Enumerated over the real topology so it scales to any NCL/NC.
# -----------------------------------------------------------------------------
echo "# --- EOTH: TCU HardFloat datapath (per core) ---"
for (( cl=0; cl<NCL; cl++ )); do
  for (( co=0; co<NC; co++ )); do
    echo "coverage exclude -scope {$(core_scope $cl $co)/execute/tcu_unit} -recursive -reason EOTH"
  done
done
echo

# -----------------------------------------------------------------------------
# 3. EUR — config-dead cache-hierarchy interfaces. L2 (per cluster) and L3
#    (per GPU) are instantiated PASSTHRU (L2_ENABLE/L3_ENABLE undefined =>
#    VX_cache_cluster .PASSTHRU(1)); the cache-side bus nets are tied off and
#    never toggle. Surgically drop ONLY the dead if[0] buses (NOT the whole
#    l2/l3 scope — the passthru mux path IS exercised and must keep its hits).
# -----------------------------------------------------------------------------
#    ⚠ GATED ON L2/L3: with the level ENABLED, VX_cache_wrap.sv:160 instantiates the
#    REAL VX_cache storage and these buses carry live traffic. Emitting the waiver
#    then would delete real coverage — the merge_coverage.sh hits-invariant gate
#    would catch it and fail the merge, but it must be correct by construction.
if (( L3 == 0 )); then
  echo "# --- EUR: L3 passthru dead cache interfaces (per GPU) ---"
  echo "coverage exclude -scope {${TOP}/l3cache/core_bus_cache_if[0]} -recursive -reason EUR"
  echo "coverage exclude -scope {${TOP}/l3cache/mem_bus_cache_if[0]}  -recursive -reason EUR"
else
  echo "# --- L3 ENABLED: cache-side buses are LIVE, no passthru waiver emitted ---"
fi
echo
if (( L2 == 0 )); then
  echo "# --- EUR: L2 passthru dead cache interfaces (per cluster) ---"
  for (( cl=0; cl<NCL; cl++ )); do
    echo "coverage exclude -scope {${TOP}/g_clusters[${cl}]/cluster/l2cache/core_bus_cache_if[0]} -recursive -reason EUR"
    echo "coverage exclude -scope {${TOP}/g_clusters[${cl}]/cluster/l2cache/mem_bus_cache_if[0]}  -recursive -reason EUR"
  done
else
  echo "# --- L2 ENABLED: cache-side buses are LIVE, no passthru waiver emitted ---"
fi
echo

# -----------------------------------------------------------------------------
# 4. ECFG — topology-structural DEAD CONDITIONS, keyed to the config.
#
#    (a) Global barrier (VX_schedule.sv:168 `~barrier.is_global && ...`): a global
#        barrier synchronizes across ALL cores of the GPU. With a SINGLE core
#        (TOTAL_CORES==1) the runtime never issues one, so `is_global` is stuck at 0
#        and the condition can never reach its 2nd input term. Structurally dead at
#        1 core; REACHABLE at >=2 cores -> emitted ONLY when TOTAL_CORES==1.
#        (`-code c` drops the condition only; the statement/branch keep their hits.)
# -----------------------------------------------------------------------------
if (( TOTAL_CORES == 1 )); then
  # ⚠ WITHDRAWN 2026-08-16 — the INTENT was right and the TOOL cannot express it.
  # `is_global` is indeed stuck at 0 with one core, so that FEC input term is
  # structurally unreachable. But Questa cannot waive ONE input term of a condition,
  # only the whole condition — and the OTHER term of `~barrier.is_global && ...` is
  # legitimately COVERED. The hits-invariant gate in merge_coverage.sh measured this
  # waiver silently discarding 1 real covered condition term at 1CL (268 -> 267),
  # which it had been doing since it was added.
  # Keeping it buys +0.03 Total and hides a covered term. Not worth it, and not
  # honest. The term stays in the denominator, uncovered, and is explained in
  # docs/COVERAGE_CEILING_ANALYSIS.md instead. Same call as VX_cache_bank.sv:263,267.
  echo "# --- ECFG: single-core global-barrier term is unreachable but NOT waived (Questa cannot waive a single FEC term; see gen script comment) ---"
  echo
else
  echo "# --- ECFG: TOTAL_CORES=${TOTAL_CORES} (>1) -> global-barrier condition is REACHABLE, NOT excluded ---"
  echo
fi

# -----------------------------------------------------------------------------
# 4b. EUR (TOGGLE) — the icache is instantiated READ-ONLY, so its write-data
#     payload is elaborated but structurally undrivable.  See OBS-033.
#
#     VX_socket.sv:106 instantiates the icache with `.WRITE_ENABLE (0)`. The cache
#     generic is fully parameterised, so `req_data.data` (CS_LINE_WIDTH = 512 b),
#     its byte-enables, and the per-bank copies of both still EXIST as nets on
#     every interface hop — they are simply never driven. Measured on the clean
#     1CL bank of 2026-08-15: the icache subtree holds 22,730 of the design's
#     85,957 missing toggle bins (26.4% of the whole toggle gap) at 55.7%, while
#     the larger dcache sits at 89.0%.
#
#     WHY THIS IS STRUCTURAL AND NOT A STIMULUS GAP — the counter-check that
#     matters: on the SAME interface, `rsp_data.data` toggles 45-46 times on every
#     one of its 512 bits. The read/fill path is fully exercised; only the write
#     direction is dead. A read-only cache cannot issue a write, at any config,
#     under any program.
#
#     This is the SAME citation already accepted for FUNCTIONAL coverage in
#     commit 5c4b70f (icache `cp_rw.wr` ignore_bins). The toggle bins produced by
#     that identical tie-off were never waived, so every bank to date reported a
#     structural impossibility as an uncovered feature.
#
#     ⚠ SCOPE DISCIPLINE — three things are deliberately NOT excluded here:
#       (1) the DCACHE write-data path. Write-through (`DCACHE_WRITEBACK=0`) is a
#           DIFFERENT mechanism and the dcache write port is genuinely driven.
#       (2) `mem_req_buf` / `mem_rsp_queue` internal `data_in`/`data_out`, even
#           though they measure 100% dead. Those buffers degenerate to passthrough
#           (`MEM_REQ_BUF_ENABLE = (NUM_BANKS != 1)`, VX_cache.sv:105, and
#           `ICACHE_MRSQ_SIZE 0`, VX_config.vh:577), and the passthru branch shows
#           the alias signature `genblk1/__unused = 47` vs `genblk2/__unused = 0`
#           — i.e. those nets may be ALIASES of live nets. Excluding an alias of a
#           covered net would hide real coverage. Left in, pending investigation.
#       (3) toggle in the icache scope wholesale (`-code t -recursive`). That would
#           drop COVERED bins too. Every rule below names a specific dead field.
#
#     Emitted per socket over the real topology, so it scales to any NCL/NC.
# -----------------------------------------------------------------------------
NUM_SOCKETS=$(( (NC + SOCKET_SIZE - 1) / SOCKET_SIZE ))
echo "# --- EUR: icache is WRITE_ENABLE(0) -> write-data payload structurally dead (OBS-033) ---"
for (( cl=0; cl<NCL; cl++ )); do
  for (( sk=0; sk<NUM_SOCKETS; sk++ )); do
    IC="${TOP}/g_clusters[${cl}]/cluster/g_sockets[${sk}]/socket/icache"
    for node in req_data.data req_data.byteen per_bank_mem_req_data per_bank_mem_req_byteen mem_req_byteen; do
      echo "coverage exclude -scope {${IC}} -recursive -togglenode {${node}} -reason EUR"
    done
  done
done
echo

# -----------------------------------------------------------------------------
# 4c. EUR (TOGGLE) — UUID upper field bits above the topology bound.  See OBS-034.
#
#     VX_uuid_gen.sv:40-41 defines the uuid EXACTLY as:
#         GNW_WIDTH = UUID_WIDTH - 32          (= 12, since UUID_WIDTH = 44)
#         g_wid     = (CORE_ID << NW_BITS) + wid
#         uuid      = { g_wid[GNW_WIDTH-1:0], counter[31:0] }
#
#     So uuid[31:0] is a per-warp instruction COUNTER and uuid[43:32] is a global
#     warp id. The largest g_wid the topology can ever produce is
#         ((TOTAL_CORES-1) << NW_BITS) + (NUM_WARPS-1)
#     and every bit above that is tied to 0 BY THE CONFIG — not by stimulus. The
#     measured per-bit toggle profile at 1CL/1C/4W matches the formula exactly:
#     bit32 = 37, bit33 = 1, bits 34..43 = 0 (g_wid maxes out at 3).
#
#     ⚠ THE COUNTER HIGH BITS ARE **NOT** WAIVED, AND THAT IS DELIBERATE.
#     Measured: uuid[0..17] toggle (46,46,...,7,7,2,1), uuid[18:31] are all 0.
#     Toggling bit k needs 2^k retired instructions ON ONE WARP (bit 31 => ~2.1e9),
#     so no run we will ever execute can reach them. But "infeasible" is NOT
#     "structurally dead": a long enough program WOULD toggle them, and this file's
#     stated principle is that reachable-but-untested coverage is never excluded.
#     They stay in the denominator and are reported as the irreducible residual.
#     Do not "clean this up" — the asymmetry is the honest part.
# -----------------------------------------------------------------------------
NW_BITS=1; while (( (1 << NW_BITS) < NW )); do NW_BITS=$(( NW_BITS + 1 )); done
(( NW <= 1 )) && NW_BITS=0
MAX_GWID=$(( ((TOTAL_CORES - 1) << NW_BITS) + (NW - 1) ))
GWID_BITS=0; while (( (1 << GWID_BITS) <= MAX_GWID )); do GWID_BITS=$(( GWID_BITS + 1 )); done
UUID_HI=43            # UUID_WIDTH-1, VX_gpu_pkg.sv:66 (NDEBUG undefined => 44)
UUID_LO=$(( 32 + GWID_BITS ))
echo "# --- EUR: uuid g_wid bits above the topology bound (OBS-034) ---"
echo "# NW_BITS=${NW_BITS} TOTAL_CORES=${TOTAL_CORES} -> max g_wid=${MAX_GWID} -> needs ${GWID_BITS} bits"
if (( UUID_LO <= UUID_HI )); then
  echo "coverage exclude -scope {${TOP}} -recursive -togglenode {uuid[${UUID_HI}:${UUID_LO}]} -reason EUR"
else
  echo "# (topology needs all ${GWID_BITS} g_wid bits -> nothing structurally dead here)"
fi
echo

# -----------------------------------------------------------------------------
# 4d. EUR (CODE) — the icache FLUSH FSM can never be entered, at any config.
#
#     PROOF CHAIN (all three links verified in the RTL, not assumed):
#       (1) VX_cache_init.sv:91 — the ONLY way a flush starts is
#           `core_bus_in_if[i].req_data.flags[MEM_REQ_FLAG_FLUSH]`.
#       (2) VX_lsu_slice.sv:73 — that flag has EXACTLY ONE producer in the whole
#           design, `req_is_fence`, and it sits on the LSU (dcache) path.
#       (3) VX_fetch.sv contains the string "flush" ZERO times — the icache's only
#           requester has no flush logic to drive it with.
#     => no instruction, in any program, at any topology, can raise flush on the
#        icache. This is a property of the instantiation, not of our stimulus.
#
#     POSITIVE CONTROL (this is what makes it a proof rather than an excuse): the
#     IDENTICAL source is FULLY COVERED on the dcache in the same run --
#     VX_cache_init 25/25 and VX_cache_flush 16/17 -- and dead on the icache
#     (14/25, 12/17). Same RTL, same suite; the only difference is which cache.
#
#     ⚠ THE `if` LINES ARE DELIBERATELY **NOT** EXCLUDED (VX_cache_init.sv:133,
#     VX_cache_flush.sv:60). Those conditions ARE evaluated every cycle and their
#     false arm is legitimately covered; excluding the line would drop 3 REAL hits.
#     Only the state BODIES -- the code reachable solely by entering a flush state
#     -- are waived. Verified: covered counts unchanged (stmt 4334, branch 2637,
#     cond 267) with 0 "had no effect".
#
#     ⚠ These are LINE-KEYED and therefore brittle if the RTL is edited. The
#     hits-invariant check in merge_coverage.sh is the guard: if a line shifts and
#     this waiver starts eating covered bins, the merge FAILS rather than silently
#     inflating the number.
# -----------------------------------------------------------------------------
NUM_ICACHES=$(( SOCKET_SIZE / 4 )); (( NUM_ICACHES < 1 )) && NUM_ICACHES=1
# VX_socket.sv:96 hardcodes .NUM_BANKS(1) for the icache -> a single g_banks[0].
CACHE_INIT_DEAD="134 135 136 137 142 147 149 151 153 154 155 156 159 162 165 166 167"
CACHE_FLUSH_DEAD="61 69 71 72 75 76 77 80 84 85 88 90"
echo "# --- EUR: icache flush FSM is structurally unenterable (OBS-035) ---"
for (( cl=0; cl<NCL; cl++ )); do
  for (( sk=0; sk<NUM_SOCKETS; sk++ )); do
    for (( ic=0; ic<NUM_ICACHES; ic++ )); do
      CS="${TOP}/g_clusters[${cl}]/cluster/g_sockets[${sk}]/socket/icache/g_cache_wrap[${ic}]/cache_wrap/g_cache/cache"
      for l in $CACHE_INIT_DEAD; do
        echo "coverage exclude -scope {${CS}/cache_init} -linerange $l -reason EUR"
      done
      for l in $CACHE_FLUSH_DEAD; do
        echo "coverage exclude -scope {${CS}/g_banks[0]/bank/cache_flush} -linerange $l -reason EUR"
      done
      # ⚠ NOT WAIVED, and this is a MEASURED decision, not an oversight:
      # VX_cache_bank.sv:263,267 `(init_valid | flush_valid)` has flush_valid
      # structurally 0 on the icache, so that FEC input term is unreachable --
      # BUT Questa cannot waive a single input term, only the whole condition,
      # and `init_valid` IS exercised (reset-time cache init). Excluding line 263
      # or 267 was measured to DROP 2 covered terms at 1CL and 4 at 2CL. Those 2
      # terms stay honestly uncovered rather than take covered bins with them.
    done
  done
done
echo

# -----------------------------------------------------------------------------
# 4e. EUR (ASSERTION) — assert_rlast_on_last_beat can never arm.
#     VX_axi_adapter.sv:262 hardwires awlen/arlen to 0, so EVERY beat is the last
#     beat and the assertion's multi-beat antecedent is never true. This is the
#     SAME restricted-master citation already used for the awlen cover-directives
#     below; a vacuous assertion is not a coverage hole.
# -----------------------------------------------------------------------------
echo "# --- EUR: rlast assertion is vacuous under a single-beat master ---"
echo "coverage exclude -srcfile ${TB}/vortex_axi_if.sv -linerange 507 -reason EUR ;# assert_rlast_on_last_beat"
echo

# -----------------------------------------------------------------------------
# 5. Structural AXI SVA cover-directives (tb/vortex_axi_if.sv g_full_axi_checks).
#    These are the DIRECTIVE MIRROR of the AXI covergroup coverpoints already waived
#    in commit 148ff78 (cp_burst / cp_len / cp_bresp / cp_rresp), with the SAME proof.
#    Applies whenever the AXI wrapper is used (all AXI configs); the merge's
#    'had no effect' guard makes it harmless on a non-AXI (mem-if) build.
#
#    (a) STRUCTURALLY IMPOSSIBLE — the Vortex AXI adapter is a *restricted master*:
#        VX_axi_adapter.sv:264 awburst = 2'b00 (FIXED only)  -> INCR/WRAP never occur
#        VX_axi_adapter.sv:262 awlen   = 8'b0  (single beat)  -> multi-beat never occurs
#        VX_axi_adapter.sv:253/288 awvalid=(..&& xbar_rw_out), arvalid=(..&& ~xbar_rw_out)
#             -> a request is read XOR write; awvalid&arvalid can never co-assert.
#    (b) UNVERIFIABLE-CLASS — bresp/rresp SLVERR/DECERR: the TB slave only returns
#        OKAY, and an AXI error response has NO SimX equivalent to check against, so an
#        error-injection test would not be end-state verifiable (same as cp_bresp/rresp).
# -----------------------------------------------------------------------------
echo "# --- EUR: structural AXI cover-directives (restricted master; mirror of 148ff78) ---"
# (a) structurally impossible
echo "coverage exclude -srcfile ${TB}/vortex_axi_if.sv -linerange 755 -reason EUR ;# aw_burst_incr  (awburst hardwired FIXED)"
echo "coverage exclude -srcfile ${TB}/vortex_axi_if.sv -linerange 757 -reason EUR ;# aw_burst_wrap  (awburst hardwired FIXED)"
echo "coverage exclude -srcfile ${TB}/vortex_axi_if.sv -linerange 779 -reason EUR ;# awlen_2to4     (awlen hardwired 0)"
echo "coverage exclude -srcfile ${TB}/vortex_axi_if.sv -linerange 781 -reason EUR ;# awlen_5to16    (awlen hardwired 0)"
echo "coverage exclude -srcfile ${TB}/vortex_axi_if.sv -linerange 783 -reason EUR ;# awlen_17to64   (awlen hardwired 0)"
echo "coverage exclude -srcfile ${TB}/vortex_axi_if.sv -linerange 785 -reason EUR ;# awlen_65to255  (awlen hardwired 0)"
echo "coverage exclude -srcfile ${TB}/vortex_axi_if.sv -linerange 789 -reason EUR ;# concurrent_aw_ar (read XOR write per port)"
# (b) unverifiable-class (TB slave OKAY-only; AXI errors not SimX-checkable)
echo "coverage exclude -srcfile ${TB}/vortex_axi_if.sv -linerange 763 -reason EUR ;# bresp_slverr   (slave OKAY-only)"
echo "coverage exclude -srcfile ${TB}/vortex_axi_if.sv -linerange 765 -reason EUR ;# bresp_decerr   (slave OKAY-only)"
echo "coverage exclude -srcfile ${TB}/vortex_axi_if.sv -linerange 771 -reason EUR ;# rresp_slverr   (slave OKAY-only)"
echo "coverage exclude -srcfile ${TB}/vortex_axi_if.sv -linerange 773 -reason EUR ;# rresp_decerr   (slave OKAY-only)"
echo

# -----------------------------------------------------------------------------
# 6. Structural / interface-dead SVA ASSERTIONS (never-triggered antecedents).
#    Only assertions whose ANTECEDENT can never hold for this design are waived;
#    the reachable ones (backpressure-stability, reset-window, outstanding-txn
#    scoreboards) are deliberately LEFT IN and closed with directed tests instead.
#
#    (a) Restricted-master AXI (antecedent needs a burst the adapter never issues):
#        assert_aw/ar_wrap_len_legal  antecedent awburst/arburst==WRAP (2'b10) — never
#        assert_aw/ar_4k_boundary     antecedent awburst/arburst==INCR (2'b01) — never
#        (adapter hardwires burst FIXED, VX_axi_adapter.sv:264/299).
#    (b) Interface-idle on an AXI build: the MEM interface is unused (DUT drives AXI),
#        so its req/rsp-stability antecedents (valid && !ready) never hold. Alive on a
#        mem-if build -> keyed to the AXI wrapper (harmless 'no effect' otherwise).
# -----------------------------------------------------------------------------
echo "# --- EUR: restricted-master AXI assertions (WRAP/INCR antecedent never holds) ---"
echo "coverage exclude -srcfile ${TB}/vortex_axi_if.sv -linerange 586 -reason EUR ;# aw_wrap_len_legal"
echo "coverage exclude -srcfile ${TB}/vortex_axi_if.sv -linerange 595 -reason EUR ;# ar_wrap_len_legal"
echo "coverage exclude -srcfile ${TB}/vortex_axi_if.sv -linerange 605 -reason EUR ;# aw_4k_boundary (INCR)"
echo "coverage exclude -srcfile ${TB}/vortex_axi_if.sv -linerange 615 -reason EUR ;# ar_4k_boundary (INCR)"
echo "# --- EUR: idle MEM-interface assertions (unused on an AXI build) ---"
echo "coverage exclude -srcfile ${TB}/vortex_mem_if.sv -linerange 135 -reason EUR ;# req_valid_stable"
echo "coverage exclude -srcfile ${TB}/vortex_mem_if.sv -linerange 138 -reason EUR ;# req_addr_stable"
echo "coverage exclude -srcfile ${TB}/vortex_mem_if.sv -linerange 152 -reason EUR ;# rsp_valid_stable"
echo "coverage exclude -srcfile ${TB}/vortex_mem_if.sv -linerange 155 -reason EUR ;# rsp_data_stable"
echo "# --- EUR: b_valid_stable unreachable — adapter hardwires m_axi_bready=1'b1 (VX_axi_adapter.sv:313) ---"
echo "coverage exclude -srcfile ${TB}/vortex_axi_if.sv -linerange 374 -reason EUR ;# b_valid_stable (bready always 1)"
echo

echo "# --- end generated exclusions (config ${NCL}CL/${NC}C/${NW}W/${NT}T) ---"
