/* MTI_DPI */

/*
 * Copyright 2002-2021 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_DPI_TYPES
#define INCLUDED_DPI_TYPES

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
void
dpi_assert(
    int inst,
    svLogic cond,
    int delay);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_f2f(
    svLogic enable,
    int dst_fmt,
    int src_fmt,
    int64_t a,
    int64_t* result);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_fadd(
    svLogic enable,
    int dst_fmt,
    int64_t a,
    int64_t b,
    const svBitVecVal* frm,
    int64_t* result,
    svBitVecVal* fflags);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_fclss(
    svLogic enable,
    int dst_fmt,
    int64_t a,
    int64_t* result);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_fdiv(
    svLogic enable,
    int dst_fmt,
    int64_t a,
    int64_t b,
    const svBitVecVal* frm,
    int64_t* result,
    svBitVecVal* fflags);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_feq(
    svLogic enable,
    int dst_fmt,
    int64_t a,
    int64_t b,
    int64_t* result,
    svBitVecVal* fflags);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_fle(
    svLogic enable,
    int dst_fmt,
    int64_t a,
    int64_t b,
    int64_t* result,
    svBitVecVal* fflags);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_flt(
    svLogic enable,
    int dst_fmt,
    int64_t a,
    int64_t b,
    int64_t* result,
    svBitVecVal* fflags);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_fmadd(
    svLogic enable,
    int dst_fmt,
    int64_t a,
    int64_t b,
    int64_t c,
    const svBitVecVal* frm,
    int64_t* result,
    svBitVecVal* fflags);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_fmax(
    svLogic enable,
    int dst_fmt,
    int64_t a,
    int64_t b,
    int64_t* result,
    svBitVecVal* fflags);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_fmin(
    svLogic enable,
    int dst_fmt,
    int64_t a,
    int64_t b,
    int64_t* result,
    svBitVecVal* fflags);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_fmsub(
    svLogic enable,
    int dst_fmt,
    int64_t a,
    int64_t b,
    int64_t c,
    const svBitVecVal* frm,
    int64_t* result,
    svBitVecVal* fflags);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_fmul(
    svLogic enable,
    int dst_fmt,
    int64_t a,
    int64_t b,
    const svBitVecVal* frm,
    int64_t* result,
    svBitVecVal* fflags);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_fnmadd(
    svLogic enable,
    int dst_fmt,
    int64_t a,
    int64_t b,
    int64_t c,
    const svBitVecVal* frm,
    int64_t* result,
    svBitVecVal* fflags);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_fnmsub(
    svLogic enable,
    int dst_fmt,
    int64_t a,
    int64_t b,
    int64_t c,
    const svBitVecVal* frm,
    int64_t* result,
    svBitVecVal* fflags);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_fsgnj(
    svLogic enable,
    int dst_fmt,
    int64_t a,
    int64_t b,
    int64_t* result);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_fsgnjn(
    svLogic enable,
    int dst_fmt,
    int64_t a,
    int64_t b,
    int64_t* result);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_fsgnjx(
    svLogic enable,
    int dst_fmt,
    int64_t a,
    int64_t b,
    int64_t* result);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_fsqrt(
    svLogic enable,
    int dst_fmt,
    int64_t a,
    const svBitVecVal* frm,
    int64_t* result,
    svBitVecVal* fflags);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_fsub(
    svLogic enable,
    int dst_fmt,
    int64_t a,
    int64_t b,
    const svBitVecVal* frm,
    int64_t* result,
    svBitVecVal* fflags);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_ftoi(
    svLogic enable,
    int dst_fmt,
    int src_fmt,
    int64_t a,
    const svBitVecVal* frm,
    int64_t* result,
    svBitVecVal* fflags);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_ftou(
    svLogic enable,
    int dst_fmt,
    int src_fmt,
    int64_t a,
    const svBitVecVal* frm,
    int64_t* result,
    svBitVecVal* fflags);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_idiv(
    svLogic enable,
    svLogic is_signed,
    int a,
    int b,
    int* quotient,
    int* remainder);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_imul(
    svLogic enable,
    svLogic is_signed_a,
    svLogic is_signed_b,
    int a,
    int b,
    int* resultl,
    int* resulth);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_itof(
    svLogic enable,
    int dst_fmt,
    int src_fmt,
    int64_t a,
    const svBitVecVal* frm,
    int64_t* result,
    svBitVecVal* fflags);

DPI_LINK_DECL DPI_DLLESPEC
int
dpi_register();

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_trace(
    int level,
    const char* format);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_trace_start();

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_trace_stop();

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_utof(
    svLogic enable,
    int dst_fmt,
    int src_fmt,
    int64_t a,
    const svBitVecVal* frm,
    int64_t* result,
    svBitVecVal* fflags);

#endif 
