"""gen_vote_shfl.py — S4: VOTE/SHFL axis for simtgen (W4).

SCOPE, established by digging the RTL/coverage model before writing any
generator code (project rule 8): `cp_vote_shfl_op` (all 8 VOTE/SHFL ops) is
ALREADY 100% covered in the current banked build by the pre-existing,
permanent `run_suite.sh` member `vote_shfl` (Vortex/tests/kernel/vote_shfl/
main.cpp) -- NOT by simtgen. No cross-coverpoint gates cp_vote_shfl_op on
active-thread-mask state (confirmed by reading tb/vx_instr_probe.sv's
alu_class_cg before writing this file: cp_vote_shfl_op is a standalone
coverpoint, unlike cross_sfu_threads for the barrier axis). This generator
therefore buys near-zero marginal coverage by design, same disclosure as
gen_barrier.py -- its value is generator-completeness and seed-diversity
evidence, not new coverage. State this plainly wherever quoted.

SAFE-ENVELOPE REUSE: every VOTE/SHFL parameter convention here mirrors the
existing `vote_shfl` kernel exactly (read before writing this file):
  - shuffle `mask` is fixed at 0 ("single subgroup spanning the whole warp")
    -- NEVER varied. Changing it repartitions sub-groups in a way this
    project has not independently verified is safe; out of scope by
    deliberate choice, not an oversight.
  - shuffle `cval` (clamp) is `NUM_THREADS - 1`, computed in the emitted C
    at COMPILE time via `#include <VX_config.h>` (NUM_THREADS is a
    compile-time macro; the Python generator cannot know it at generation
    time) -- exactly the existing kernel's own pattern.
  - the shift amount `bval` is seed-drawn but reduced mod NUM_THREADS in
    the emitted C, so it can never exceed the clamp for whatever config the
    generated kernel is actually compiled against.

Per-seed variety (constraint 6, the only randomness source is the
caller-owned `rng`): the three VOTE predicate shapes (p_all/p_par/p_uni) and
the SHFL shift amount are lane-and-seed-derived; additionally, lanes below a
seed-drawn threshold are PEELED OUT (an `if (tid < threshold)` guard) before
the whole vote/shfl block executes, so different seeds exercise VOTE under
genuinely varying active-thread-count contexts -- matching the axis's
originally-stated "under divergent masks" intent even though the coverpoint
itself does not require it.

HARD CONSTRAINTS (same six as the other axes):
  1. RACE-FREE: only `g_out[tid]`, the thread's own slot, is written.
  2. Peel guard is a plain C `if`; the VOTE/SHFL ops themselves are
     intrinsics (inline asm internally, same as every SFU/ALU-custom op in
     this project) -- the established, accepted mechanism, not a
     constraint-2 violation (which targets hand-assembled DIVERGENT
     BRANCHES specifically).
  3. DEVICE-DERIVED GRID: `vx_num_cores()*vx_num_warps()*vx_num_threads()`
     at runtime, mirrors the existing `vote_shfl` kernel and gen_memory.py.
  4. NO SELF-CHECK: SimX lockstep + end-state compare are the checker.
  5. BOUNDED LIVE VALUES: at most ~10 locals live at once (tid, lane,
     value, three predicates, four vote results, four shuffle results are
     never all simultaneously live -- see the template), under the
     ~12-16 threshold.
  6. SEEDED/DETERMINISTIC: only `rng` is touched for randomness.

Original algorithm; no FuzzGPU code read or reused (see knobs.py header).
"""

from __future__ import annotations

from knobs import VoteShflKnobs, DEFAULT_VOTE_SHFL_KNOBS


_MAIN_TEMPLATE = """\
// {name} — simtgen-generated (S4 VOTE/SHFL axis). Seed: {seed}.
// Peel threshold: {peel_threshold} (of NUM_THREADS lanes per warp).
// Generated by scripts/simtgen/gen_vote_shfl.py -- original tool, no
// FuzzGPU code vendored or transliterated (see knobs.py header). Safe
// parameter envelope (mask=0, cval=NUM_THREADS-1) mirrors the existing,
// already-validated Vortex/tests/kernel/vote_shfl/main.cpp exactly.

#include <stdint.h>
#include <vx_intrinsics.h>
#include <vx_spawn.h>
#include <VX_config.h>      // NUM_CLUSTERS, NUM_CORES, NUM_WARPS, NUM_THREADS

#define MAX_TOTAL 128

typedef struct {{ uint32_t *out; }} {name}_args_t;

volatile uint32_t g_out[MAX_TOTAL];

void {name}_kernel({name}_args_t *__UNIFORM__ args) {{
  int tid  = blockIdx.x;
  int lane = tid % NUM_THREADS;          // lane within this warp
  uint32_t r = 0;

  // Peel guard: lanes >= threshold sit this block out entirely, so VOTE
  // sees a genuinely partial active mask on peeled seeds (threshold <
  // NUM_THREADS) as well as the full warp (unpeeled seeds).
  if (lane < {peel_threshold}) {{
    int value = {value_base} + lane * {value_mul};

    int p_all = (value >= 0);                       // uniformly true  -> vote_all
    int p_par = (lane ^ {xor_const}) & 1;            // mixed           -> vote_any/ballot
    int p_uni = (value < 1000000);                   // uniformly true  -> vote_uni

    int va = vx_vote_all   (p_all);
    int vy = vx_vote_any   (p_par);
    int vu = vx_vote_uni   (p_uni);
    int vb = vx_vote_ballot(p_par);

    int mask  = 0;                       // fixed: single subgroup spanning the warp
    int clamp = NUM_THREADS - 1;
    int bval  = {bval_seed} % NUM_THREADS;
    int su = vx_shfl_up  (value, bval, clamp, mask);
    int sd = vx_shfl_down(value, bval, clamp, mask);
    int sf = vx_shfl_bfly(value, bval, clamp, mask);
    int si = vx_shfl_idx (value, bval, clamp, mask);

    r = (uint32_t)(va ^ vy ^ vu ^ vb ^ su ^ sd ^ sf ^ si ^ value);
  }}

  args->out[tid] = r;
}}

int main() {{
  {name}_args_t args; args.out = (uint32_t *)g_out;
  uint32_t total = (uint32_t)vx_num_cores() * vx_num_warps() * vx_num_threads();
  if (total > MAX_TOTAL) total = MAX_TOTAL;
  vx_spawn_threads(1, &total, nullptr, (vx_kernel_func_cb){name}_kernel, &args);
  return 0;   // scoreboard (DUT vs SimX end-state of g_out) is the authority
}}
"""


def generate(rng, name: str = "simtgen_vote_shfl", seed=None, knobs: VoteShflKnobs = None) -> str:
    """Generate one VOTE/SHFL-axis kernel's main.cpp source text.

    `rng` MUST be the caller-owned `random.Random` instance (constraint 6).
    peel_threshold is drawn generously (>=2) so at least a partial warp is
    always active -- an all-lanes-peeled program would be a vacuous run
    (OBS-029 class), not real stimulus.
    """
    if knobs is None:
        knobs = DEFAULT_VOTE_SHFL_KNOBS

    # Peel threshold in [2, 32] -- a Python-side upper bound; the emitted C
    # itself takes `lane = tid % NUM_THREADS`, so an over-wide threshold
    # simply never triggers the peel on a narrower build (degrades
    # gracefully, same convention as gen_divergence.py's peel_levels knob).
    peel_threshold = rng.randint(2, 32)

    return _MAIN_TEMPLATE.format(
        name=name,
        seed=seed,
        peel_threshold=peel_threshold,
        value_base=rng.randint(1, 97),
        value_mul=rng.randint(1, 13),
        xor_const=rng.randint(0, 15),
        bval_seed=rng.randint(0, knobs.max_bval),
    )
