"""gen_barrier.py — S3: barrier-topology axis for simtgen (W4).

SCOPE, established by digging the RTL/coverage model before writing any
generator code (project rule 8: plan/read before touching anything):

  - `cross_sfu_threads` (bar op x active-thread-mask state) and
    `cp_vote_shfl_op` (this axis's sibling, gen_vote_shfl.py) are ALREADY
    100% covered in the current banked build via pre-existing, permanent
    `run_suite.sh` members (`bar_masks`, `sfu_masks`, `vote_shfl`) -- NOT
    via simtgen. This generator therefore buys near-zero marginal coverage
    by design; its value is generator-completeness (the papers no longer
    have to say "barrier topology ... declared but not implemented") and
    seed-diversity/robustness evidence (the same category of result as
    OBS-046's riscv-dv seed farm), not new coverage. State this plainly
    wherever this axis's numbers are quoted -- do not imply a coverage win
    that isn't real.
  - WSPAWN is deliberately NEVER touched by this generator. `cross_sfu_threads`
    already carries a structural waiver (`vortex_coverage_collector`-adjacent
    tb/vx_instr_probe.sv) for <wspawn,partial|uniform>: wspawn is a
    runtime-only primitive issued exclusively from the single-thread spawn
    bootstrap (Vortex/kernel/src/vx_spawn.c:259); a generated SIMT kernel
    body issuing wspawn would be exactly the "broken/unsafe" case that
    waiver's own comment warns about, not legitimate barrier-topology
    stimulus. This generator only ever calls `vx_barrier`.

DEADLOCK SAFETY, mirrored exactly from the proven `bar_masks` kernel
(Vortex/tests/kernel/bar_masks/main.cpp, read before writing this file):
  - Exactly ONE warp is spawned (grid size == threads-per-warp), so every
    `vx_barrier(id, 1)` call's `num_warps` argument is always 1 -- the
    barrier is satisfied by this warp's own arrival and releases
    immediately. No other warp is ever expected, so issuing it under a
    divergent (partial-mask) thread subset cannot hang: the barrier is
    warp-level, diverged-inactive lanes simply don't participate, and
    reconvergence (vx_join) is unaffected. `num_warps` is NEVER varied by
    this generator -- that is the one invariant that makes single-warp
    barrier stimulus deadlock-free by construction, and departing from it
    (multi-warp `num_warps`) would need a companion warp actually arriving,
    which nothing in a lone generated kernel can guarantee.

HARD CONSTRAINTS (same six as gen_divergence.py / gen_memory.py):
  1. RACE-FREE: only `out_buf[i]`, the thread's own slot, is written.
  2. REAL C CONTROL FLOW for the peel structure (plain `if`); only the
     barrier call itself is necessarily an intrinsic (`vx_barrier` is
     inline asm internally, same as every SFU/ALU-custom op in this
     project -- see vx_intrinsics.h; this is the established, accepted
     mechanism for these ops project-wide, not a constraint-2 violation,
     which is specifically about hand-assembling DIVERGENT BRANCHES).
  3. DEVICE-DERIVED GRID: grid size is `vx_num_threads()` at runtime (one
     warp's worth) -- never hardcoded, matches `bar_masks` exactly.
  4. NO SELF-CHECK: SimX lockstep + end-state compare are the checker.
  5. BOUNDED LIVE VALUES: the peel chain carries a single accumulator `r`
     plus one new local per level; capped by `peel_depth` (<=3, well under
     the spill threshold).
  6. SEEDED/DETERMINISTIC: the caller-owned `rng` is the only randomness
     source (peel depth, per-level barrier ids, per-level literals).

Original algorithm; no FuzzGPU code read or reused (see knobs.py header).
"""

from __future__ import annotations
from dataclasses import dataclass

from knobs import BarrierKnobs, DEFAULT_BARRIER_KNOBS


_MAIN_TEMPLATE = """\
// {name} — simtgen-generated (S3 barrier-topology axis). Seed: {seed}.
// Peel depth: {peel_depth}. Generated by scripts/simtgen/gen_barrier.py --
// original tool, no FuzzGPU code vendored or transliterated (see knobs.py
// header). See that file's module docstring for the deadlock-safety
// argument (single warp, num_warps==1 on every vx_barrier call, mirrored
// from the proven bar_masks kernel).

#include <vx_intrinsics.h>
#include <vx_spawn.h>

#define OPQ(x) __asm__ volatile("" : "+r"(x))   // optimization barrier (real control flow)
#define MAXNT {max_nt}

typedef struct {{ int *in; int *out; int nt; }} {name}_args_t;

// Peel thresholds are computed HERE, at runtime, from the REAL nt
// (vx_num_threads()) -- never baked in as Python-side literals. A literal
// threshold >= the build's actual NUM_THREADS would peel nothing (every
// lane satisfies tid < threshold), silently degrading to all-uniform
// stimulus regardless of the generator's seed. Runtime derivation is what
// makes the peel chain meaningful at ANY THREADS-per-warp config.
static inline int {name}_chain(int r, int tid, int nt) {{
  int t = nt - 1; if (t < 1) t = 1;
{peel_body}
  return r;
}}

int in_buf[MAXNT];
volatile int out_buf[MAXNT];

void {name}_kernel({name}_args_t *__UNIFORM__ args) {{
  int i = blockIdx.x;
  args->out[i] = {name}_chain(args->in[i], i & (MAXNT - 1), args->nt);
}}

int main() {{
  int nt = vx_num_threads();          // threads per warp -> exactly one warp spawned
  if (nt < 1)     nt = 1;
  if (nt > MAXNT) nt = MAXNT;
  for (int i = 0; i < nt; i++) {{ in_buf[i] = i * {in_mul} + {in_add}; out_buf[i] = 0; }}

  {name}_args_t args;
  args.in  = in_buf;
  args.out = (int*)out_buf;
  args.nt  = nt;

  uint32_t total = nt;                 // one warp's worth of threads
  vx_spawn_threads(1, &total, nullptr, (vx_kernel_func_cb){name}_kernel, &args);

  // No self-check (constraint 4): SimX lockstep + end-state compare verify.
  return 0;
}}
"""


def _render_peel_body(rng, peel_depth: int) -> str:
    """Build the C text for a nested peel chain: level k is active for
    `tid < t` where `t` is DECREMENTED (clamped at 1) once per level at
    RUNTIME, starting from `nt - 1` (mirrors gen_divergence.py's linear
    thread-peeling shape, the only construction that nests real divergent
    splits before the active set collapses -- OBS-059, and matches the
    proven bar_masks kernel's own descending-threshold pattern, just
    computed from the real nt instead of a hardcoded 3/2). Every level
    fires exactly one `vx_barrier(id,1)` -- id and the per-level literal
    are seed-drawn (constraint 6), num_warps is hardcoded 1 everywhere
    (the deadlock-safety invariant, never varied). Clamping at 1 means a
    peel_depth deeper than nt-1 degrades gracefully (repeats the
    one-thread-active level rather than going empty/negative) instead of
    ever producing a threshold that admits zero lanes.
    """
    lines = []
    indent = "  "
    top_id = rng.randint(0, 255)
    lines.append(f"{indent}vx_barrier({top_id}, 1);          OPQ(r);   // bar uniform")
    lines.append(f"{indent}r += {rng.randint(1, 31)};")

    for level in range(peel_depth):
        bid = rng.randint(0, 255)
        lit = rng.randint(1, 63)
        lines.append(f"{indent}if (tid < t) {{ OPQ(r);")
        indent += "  "
        lines.append(f"{indent}vx_barrier({bid}, 1);        OPQ(r);   // bar partial (level {level})")
        lines.append(f"{indent}r += {lit};")
        lines.append(f"{indent}t = t - 1; if (t < 1) t = 1;")
    for _ in range(peel_depth):
        indent = indent[:-2]
        lines.append(f"{indent}}}")
        lines.append(f"{indent}OPQ(r);")
    return "\n".join(lines)


def generate(rng, name: str = "simtgen_barrier", seed=None, knobs: BarrierKnobs = None) -> str:
    """Generate one barrier-axis kernel's main.cpp source text.

    `rng` MUST be the caller-owned `random.Random` instance (constraint 6).
    """
    if knobs is None:
        knobs = DEFAULT_BARRIER_KNOBS

    peel_depth = rng.randint(knobs.min_peel_depth, knobs.max_peel_depth)
    peel_body = _render_peel_body(rng, peel_depth)

    return _MAIN_TEMPLATE.format(
        name=name,
        seed=seed,
        peel_depth=peel_depth,
        max_nt=knobs.max_nt,
        peel_body=peel_body,
        in_mul=rng.randint(2, 11),
        in_add=rng.randint(0, 9),
    )
