"""gen_memory.py — S2: memory-pattern axis for simtgen.

Emits a Vortex device kernel that exercises two independent probes in one
program:

  (A) GLOBAL memory access pattern (targets `coalesce_cg` in
      tb/vx_coalescer_probe.sv, bound on VX_mem_coalescer). Per seed, one of
      three patterns is chosen for a per-thread READ from `in_buf`:
        - "coalescable" : idx = i               -> consecutive lanes touch
          consecutive words -> VX_mem_coalescer's own `coalesce_kind==0`
          (full_coalesced, vx_coalescer_probe.sv:193-196).
        - "partial"     : idx = (i*2) % MAX_TOTAL -> lanes share dcache
          words two-at-a-time (DATA_RATIO=4 words/dcache-word at the
          project's primary config, see vx_coalescer_probe.sv header) ->
          `coalesce_kind==1` (partial).
        - "scattered"   : idx = (i*STRIDE) % MAX_TOTAL, STRIDE drawn from a
          pool of values >= DATA_RATIO so no two lanes of a warp share a
          dcache word -> `coalesce_kind==2` (full_scatter).
      The WRITE is always to `out_buf[i]` -- the thread's own slot -- so this
      never introduces a data race (constraint 1); only the READ address
      varies, and concurrent reads of the same address are not a hazard.

  (B) LOCAL memory (scratchpad) BANK-HOSTILE access (targets G-9's
      `lmem_bank_cg.cp_bank_conflict.conflict` bin in
      tb/vx_lmem_probe.sv, bound on VX_local_mem) -- present in EVERY
      generated memory-axis program, not just a random subset, because this
      is the one concrete, currently-open acceptance criterion this axis
      exists to close.

      RTL-DERIVED BANK FORMULA (not guessed):
        Vortex/hw/rtl/mem/VX_local_mem.sv:65-71 --
          `req_bank_idx[i] = mem_bus_if[i].req_data.addr[0 +: BANK_SEL_BITS]`
        i.e. the bank is the low BANK_SEL_BITS = clog2(NUM_BANKS) bits of the
        WORD address (this LMEM instance is word-addressed: ADDR_WIDTH ==
        BANK_ADDR_WIDTH + BANK_SEL_BITS, static-asserted at :58-59;
        `lmem` below is a `volatile int *`, so `lmem[k]` IS a word address).
        NUM_BANKS for this LMEM instance is `LMEM_NUM_BANKS`, which
        VX_config.vh:677-682 defaults to `NUM_LSU_LANES` (== `SIMD_WIDTH`,
        i.e. the project's THREADS-per-warp knob) whenever LMEM is enabled
        and no override is given -- confirmed this project never overrides
        it (grep of hw/rtl and sim/uvmsim turns up no `LMEM_NUM_BANKS`
        define). So for this project's builds, NUM_BANKS == nt
        (`vx_num_threads()`), and the probe's own header (vx_lmem_probe.sv,
        top-of-file bind comment) independently confirms NUM_BANKS=4 at the
        1CL/1C/4W/4T primary config -- consistent with NUM_LSU_LANES=4 there.

      CONSTRUCTION: within one warp, lane `tid` (0..nt-1) is given LMEM word
      address `base + tid*nt`. Every lane's address differs (constraint 1:
      no two threads share an address, no race) but
        (base + tid*nt) mod nt == base mod nt   for EVERY tid (the tid*nt
      term vanishes mod nt), so all nt lanes of the warp land in the SAME
      bank on the SAME cycle -- the RTL's own crossbar can only accept one
      winner per bank per cycle (vx_lmem_probe.sv's own comment), so this is
      exactly the >=2-same-bank-same-cycle event `cp_bank_conflict.conflict`
      counts. This is a BANK collision on DIFFERENT addresses, not a data
      race (constraint 1's explicit carve-out).

Original algorithm; no FuzzGPU code read or reused (see knobs.py header).
HARD CONSTRAINTS 1/3/4/5/6 are enforced the same way gen_divergence.py
enforces them -- see the per-constraint notes inline below.
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import List

# STRIDE pool for the "scattered" pattern: each value is >= DATA_RATIO (4 at
# the primary config; kept >=5 here to be safely scattered even if the ratio
# ever changes) and coprime-ish with common small MAX_TOTAL values so lanes
# genuinely spread out rather than aliasing back onto each other.
_SCATTER_STRIDES = [5, 7, 11, 13, 17, 19]

_PATTERNS = ("coalescable", "partial", "scattered")


@dataclass
class MemoryKnobs:
    """S2 knobs. max_live_values mirrors DivergenceKnobs' bound (constraint
    5): this generator's body only ever holds `i, nt, idx, slot, base, v`
    live at once (well under the ~12-16 threshold)."""
    max_total: int = 128
    slots_per_core: int = 64   # power of two, must be a multiple of every
                                # nt this project builds with (2/4/8/16/32/64)


DEFAULT_MEMORY_KNOBS = MemoryKnobs()


_MAIN_TEMPLATE = """\
// {name} — simtgen-generated (S2 memory-pattern axis). Seed: {seed}.
// Global pattern: {pattern}. Generated by scripts/simtgen/gen_memory.py —
// original tool, no FuzzGPU code vendored or transliterated (see knobs.py
// header). See that file's module docstring for the RTL-derived bank-index
// formula and coalescing-pattern rationale.

#include <vx_intrinsics.h>
#include <vx_spawn.h>

#define MAX_TOTAL       {max_total}
#define SLOTS_PER_CORE  {slots_per_core}
#define GLOBAL_STRIDE   {stride}

volatile int in_buf[MAX_TOTAL] = {{
{in_buf_init}
}};
volatile int out_buf[MAX_TOTAL];
volatile int lmem_out[MAX_TOTAL];

typedef struct {{ int *out; int *lout; int nt; }} {name}_args_t;

void {name}_kernel({name}_args_t *__UNIFORM__ args) {{
  int i  = blockIdx.x;
  int nt = args->nt;

  // --- (A) global-memory pattern (coalesce_cg) -----------------------
  // READ address varies by pattern; WRITE is always the thread's OWN
  // slot out_buf[i] (constraint 1: race-free by construction).
  int idx = ({idx_expr}) % MAX_TOTAL;
  if (idx < 0) idx += MAX_TOTAL;
  int v = in_buf[idx];
  args->out[i] = v * 3 + 1;

  // --- (B) LMEM bank-hostile pattern (G-9 cp_bank_conflict.conflict) --
  // base is per-warp (shared across the nt lanes of this warp); each lane
  // adds tid*nt words -> distinct address, same bank (see module docstring
  // for the mod-nt derivation from VX_local_mem.sv's own bank-select).
  int wid = i / nt;
  int tid = i % nt;
  // Per-warp base MUST be spaced by at least nt*nt words so different warps'
  // nt-wide, nt-strided slot windows never overlap (an earlier version used
  // wid*nt here, which aliased adjacent warps onto the SAME address -- a
  // real cross-warp write race, not a bank conflict -- caught by an actual
  // scoreboard MEM MISMATCH before this fix; see gen_memory.py history).
  int base = (wid * nt * nt) & (SLOTS_PER_CORE - 1);
  int slot = (base + tid * nt) & (SLOTS_PER_CORE - 1);
  volatile int *lmem = (volatile int *)csr_read(VX_CSR_LOCAL_MEM_BASE);
  lmem[slot] = tid * 131 + 7;
  int lv = lmem[slot];
  args->lout[i] = lv;
}}

int main() {{
  int nt = vx_num_threads();
  if (nt < 1) nt = 1;

  // NON-VACUITY GUARD (OBS-029 pattern, mirrors lmem_stress.main.cpp): if
  // LMEM base reads as 0, the CSR path is not doing what's assumed and the
  // bank-hostile half of this program is testing nothing.
  if ((unsigned)csr_read(VX_CSR_LOCAL_MEM_BASE) == 0u) return 1;

  {name}_args_t args;
  args.out  = (int *)out_buf;
  args.lout = (int *)lmem_out;
  args.nt   = nt;

  // Device-derived grid (constraint 3) -- never hardcoded.
  uint32_t total = (uint32_t)vx_num_cores() * vx_num_warps() * vx_num_threads();
  if (total > MAX_TOTAL) total = MAX_TOTAL;
  vx_spawn_threads(1, &total, nullptr, (vx_kernel_func_cb){name}_kernel, &args);

  // No self-check (constraint 4): SimX lockstep + end-state compare verify.
  return 0;
}}
"""

_IDX_EXPRS = {
    "coalescable": "i",
    "partial": "i * 2",
    "scattered": "i * GLOBAL_STRIDE",
}


def generate(rng, name: str = "simtgen_mem", seed=None, knobs: MemoryKnobs = None) -> str:
    """Generate one memory-axis kernel's main.cpp source text.

    `rng` MUST be the caller-owned `random.Random` instance (constraint 6).
    Two rng draws happen here: the global-access pattern choice and (only
    for "scattered") the stride value -- both go through `rng`, nothing
    else. `in_buf`'s contents are also seed-derived (via rng) so distinct
    seeds get distinct data without ever touching the `random` module's
    global state.
    """
    if knobs is None:
        knobs = DEFAULT_MEMORY_KNOBS

    pattern = rng.choice(_PATTERNS)
    stride = rng.choice(_SCATTER_STRIDES) if pattern == "scattered" else 1

    # Bounded, deterministic in_buf init -- plain small ints, no need for a
    # wide range since only the coalescing ADDRESS pattern is under test.
    values = [rng.randint(1, 997) for _ in range(knobs.max_total)]
    in_buf_init = ",\n".join(
        "  " + ", ".join(str(v) for v in values[i:i + 16])
        for i in range(0, len(values), 16)
    )

    return _MAIN_TEMPLATE.format(
        name=name,
        seed=seed,
        pattern=pattern,
        max_total=knobs.max_total,
        slots_per_core=knobs.slots_per_core,
        stride=stride,
        idx_expr=_IDX_EXPRS[pattern],
        in_buf_init=in_buf_init,
    )
